# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: amz_ups.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='amz_ups.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\ramz_ups.proto\"+\n\tUAConnect\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x1c\n\x0b\x41UConnected\x12\r\n\x05\x65rror\x18\x01 \x01(\t\":\n\x08\x41Product\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x13\n\x0b\x64\x65scription\x18\x02 \x02(\t\x12\r\n\x05\x63ount\x18\x03 \x02(\x05\"t\n\x08GoPickUp\x12\x0c\n\x04whid\x18\x01 \x02(\x05\x12\r\n\x05\x64st_x\x18\x02 \x02(\x05\x12\r\n\x05\x64st_y\x18\x03 \x02(\x05\x12\x11\n\tpackageid\x18\x04 \x02(\x03\x12\x19\n\x06things\x18\x05 \x03(\x0b\x32\t.AProduct\x12\x0e\n\x06userid\x18\x06 \x01(\t\" \n\x0bLoadSuccess\x12\x11\n\tpackageid\x18\x01 \x02(\x03\",\n\x11GetDeliveryStatus\x12\x17\n\x0ftracking_number\x18\x01 \x02(\x05\";\n\rPackageReqAck\x12\x17\n\x0ftracking_number\x18\x01 \x02(\x05\x12\x11\n\tpackageid\x18\x02 \x02(\x03\"2\n\x0cTruckArrived\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\x0f\n\x07truckid\x18\x02 \x02(\x05\"%\n\x10LoadConfirmation\x12\x11\n\tpackageid\x18\x01 \x02(\x03\"?\n\x14ReturnDeliveryStatus\x12\x17\n\x0ftracking_number\x18\x01 \x02(\x03\x12\x0e\n\x06status\x18\x02 \x02(\t\"&\n\x11\x44\x65liveryCompleted\x12\x11\n\tpackageid\x18\x01 \x02(\x03\"\x8e\x01\n\nAUMessages\x12\x1c\n\tgopickups\x18\x01 \x03(\x0b\x32\t.GoPickUp\x12\x1c\n\x06loaded\x18\x02 \x03(\x0b\x32\x0c.LoadSuccess\x12#\n\x07queries\x18\x03 \x03(\x0b\x32\x12.GetDeliveryStatus\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x10\n\x08\x66inished\x18\x05 \x01(\x08\"\xf5\x01\n\nUAMessages\x12(\n\x10\x63reatedShipments\x18\x01 \x03(\x0b\x32\x0e.PackageReqAck\x12\x1e\n\x07\x61rrived\x18\x02 \x03(\x0b\x32\r.TruckArrived\x12(\n\rloadedConfirm\x18\x03 \x03(\x0b\x32\x11.LoadConfirmation\x12+\n\x0cqueryResults\x18\x04 \x03(\x0b\x32\x15.ReturnDeliveryStatus\x12%\n\tdelivered\x18\x05 \x03(\x0b\x32\x12.DeliveryCompleted\x12\r\n\x05\x65rror\x18\x06 \x01(\t\x12\x10\n\x08\x66inished\x18\x07 \x01(\x08')
)




_UACONNECT = _descriptor.Descriptor(
  name='UAConnect',
  full_name='UAConnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='UAConnect.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='UAConnect.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=60,
)


_AUCONNECTED = _descriptor.Descriptor(
  name='AUConnected',
  full_name='AUConnected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='AUConnected.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=90,
)


_APRODUCT = _descriptor.Descriptor(
  name='AProduct',
  full_name='AProduct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='AProduct.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='AProduct.description', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='AProduct.count', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=150,
)


_GOPICKUP = _descriptor.Descriptor(
  name='GoPickUp',
  full_name='GoPickUp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='whid', full_name='GoPickUp.whid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_x', full_name='GoPickUp.dst_x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_y', full_name='GoPickUp.dst_y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packageid', full_name='GoPickUp.packageid', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='things', full_name='GoPickUp.things', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userid', full_name='GoPickUp.userid', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=268,
)


_LOADSUCCESS = _descriptor.Descriptor(
  name='LoadSuccess',
  full_name='LoadSuccess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='LoadSuccess.packageid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=302,
)


_GETDELIVERYSTATUS = _descriptor.Descriptor(
  name='GetDeliveryStatus',
  full_name='GetDeliveryStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracking_number', full_name='GetDeliveryStatus.tracking_number', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=348,
)


_PACKAGEREQACK = _descriptor.Descriptor(
  name='PackageReqAck',
  full_name='PackageReqAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracking_number', full_name='PackageReqAck.tracking_number', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packageid', full_name='PackageReqAck.packageid', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=409,
)


_TRUCKARRIVED = _descriptor.Descriptor(
  name='TruckArrived',
  full_name='TruckArrived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='TruckArrived.packageid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='truckid', full_name='TruckArrived.truckid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=461,
)


_LOADCONFIRMATION = _descriptor.Descriptor(
  name='LoadConfirmation',
  full_name='LoadConfirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='LoadConfirmation.packageid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=500,
)


_RETURNDELIVERYSTATUS = _descriptor.Descriptor(
  name='ReturnDeliveryStatus',
  full_name='ReturnDeliveryStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracking_number', full_name='ReturnDeliveryStatus.tracking_number', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='ReturnDeliveryStatus.status', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=565,
)


_DELIVERYCOMPLETED = _descriptor.Descriptor(
  name='DeliveryCompleted',
  full_name='DeliveryCompleted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='DeliveryCompleted.packageid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=567,
  serialized_end=605,
)


_AUMESSAGES = _descriptor.Descriptor(
  name='AUMessages',
  full_name='AUMessages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gopickups', full_name='AUMessages.gopickups', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loaded', full_name='AUMessages.loaded', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queries', full_name='AUMessages.queries', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='AUMessages.error', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='finished', full_name='AUMessages.finished', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=608,
  serialized_end=750,
)


_UAMESSAGES = _descriptor.Descriptor(
  name='UAMessages',
  full_name='UAMessages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='createdShipments', full_name='UAMessages.createdShipments', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arrived', full_name='UAMessages.arrived', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loadedConfirm', full_name='UAMessages.loadedConfirm', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queryResults', full_name='UAMessages.queryResults', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delivered', full_name='UAMessages.delivered', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='UAMessages.error', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='finished', full_name='UAMessages.finished', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=753,
  serialized_end=998,
)

_GOPICKUP.fields_by_name['things'].message_type = _APRODUCT
_AUMESSAGES.fields_by_name['gopickups'].message_type = _GOPICKUP
_AUMESSAGES.fields_by_name['loaded'].message_type = _LOADSUCCESS
_AUMESSAGES.fields_by_name['queries'].message_type = _GETDELIVERYSTATUS
_UAMESSAGES.fields_by_name['createdShipments'].message_type = _PACKAGEREQACK
_UAMESSAGES.fields_by_name['arrived'].message_type = _TRUCKARRIVED
_UAMESSAGES.fields_by_name['loadedConfirm'].message_type = _LOADCONFIRMATION
_UAMESSAGES.fields_by_name['queryResults'].message_type = _RETURNDELIVERYSTATUS
_UAMESSAGES.fields_by_name['delivered'].message_type = _DELIVERYCOMPLETED
DESCRIPTOR.message_types_by_name['UAConnect'] = _UACONNECT
DESCRIPTOR.message_types_by_name['AUConnected'] = _AUCONNECTED
DESCRIPTOR.message_types_by_name['AProduct'] = _APRODUCT
DESCRIPTOR.message_types_by_name['GoPickUp'] = _GOPICKUP
DESCRIPTOR.message_types_by_name['LoadSuccess'] = _LOADSUCCESS
DESCRIPTOR.message_types_by_name['GetDeliveryStatus'] = _GETDELIVERYSTATUS
DESCRIPTOR.message_types_by_name['PackageReqAck'] = _PACKAGEREQACK
DESCRIPTOR.message_types_by_name['TruckArrived'] = _TRUCKARRIVED
DESCRIPTOR.message_types_by_name['LoadConfirmation'] = _LOADCONFIRMATION
DESCRIPTOR.message_types_by_name['ReturnDeliveryStatus'] = _RETURNDELIVERYSTATUS
DESCRIPTOR.message_types_by_name['DeliveryCompleted'] = _DELIVERYCOMPLETED
DESCRIPTOR.message_types_by_name['AUMessages'] = _AUMESSAGES
DESCRIPTOR.message_types_by_name['UAMessages'] = _UAMESSAGES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UAConnect = _reflection.GeneratedProtocolMessageType('UAConnect', (_message.Message,), dict(
  DESCRIPTOR = _UACONNECT,
  __module__ = 'amz_ups_pb2'
  # @@protoc_insertion_point(class_scope:UAConnect)
  ))
_sym_db.RegisterMessage(UAConnect)

AUConnected = _reflection.GeneratedProtocolMessageType('AUConnected', (_message.Message,), dict(
  DESCRIPTOR = _AUCONNECTED,
  __module__ = 'amz_ups_pb2'
  # @@protoc_insertion_point(class_scope:AUConnected)
  ))
_sym_db.RegisterMessage(AUConnected)

AProduct = _reflection.GeneratedProtocolMessageType('AProduct', (_message.Message,), dict(
  DESCRIPTOR = _APRODUCT,
  __module__ = 'amz_ups_pb2'
  # @@protoc_insertion_point(class_scope:AProduct)
  ))
_sym_db.RegisterMessage(AProduct)

GoPickUp = _reflection.GeneratedProtocolMessageType('GoPickUp', (_message.Message,), dict(
  DESCRIPTOR = _GOPICKUP,
  __module__ = 'amz_ups_pb2'
  # @@protoc_insertion_point(class_scope:GoPickUp)
  ))
_sym_db.RegisterMessage(GoPickUp)

LoadSuccess = _reflection.GeneratedProtocolMessageType('LoadSuccess', (_message.Message,), dict(
  DESCRIPTOR = _LOADSUCCESS,
  __module__ = 'amz_ups_pb2'
  # @@protoc_insertion_point(class_scope:LoadSuccess)
  ))
_sym_db.RegisterMessage(LoadSuccess)

GetDeliveryStatus = _reflection.GeneratedProtocolMessageType('GetDeliveryStatus', (_message.Message,), dict(
  DESCRIPTOR = _GETDELIVERYSTATUS,
  __module__ = 'amz_ups_pb2'
  # @@protoc_insertion_point(class_scope:GetDeliveryStatus)
  ))
_sym_db.RegisterMessage(GetDeliveryStatus)

PackageReqAck = _reflection.GeneratedProtocolMessageType('PackageReqAck', (_message.Message,), dict(
  DESCRIPTOR = _PACKAGEREQACK,
  __module__ = 'amz_ups_pb2'
  # @@protoc_insertion_point(class_scope:PackageReqAck)
  ))
_sym_db.RegisterMessage(PackageReqAck)

TruckArrived = _reflection.GeneratedProtocolMessageType('TruckArrived', (_message.Message,), dict(
  DESCRIPTOR = _TRUCKARRIVED,
  __module__ = 'amz_ups_pb2'
  # @@protoc_insertion_point(class_scope:TruckArrived)
  ))
_sym_db.RegisterMessage(TruckArrived)

LoadConfirmation = _reflection.GeneratedProtocolMessageType('LoadConfirmation', (_message.Message,), dict(
  DESCRIPTOR = _LOADCONFIRMATION,
  __module__ = 'amz_ups_pb2'
  # @@protoc_insertion_point(class_scope:LoadConfirmation)
  ))
_sym_db.RegisterMessage(LoadConfirmation)

ReturnDeliveryStatus = _reflection.GeneratedProtocolMessageType('ReturnDeliveryStatus', (_message.Message,), dict(
  DESCRIPTOR = _RETURNDELIVERYSTATUS,
  __module__ = 'amz_ups_pb2'
  # @@protoc_insertion_point(class_scope:ReturnDeliveryStatus)
  ))
_sym_db.RegisterMessage(ReturnDeliveryStatus)

DeliveryCompleted = _reflection.GeneratedProtocolMessageType('DeliveryCompleted', (_message.Message,), dict(
  DESCRIPTOR = _DELIVERYCOMPLETED,
  __module__ = 'amz_ups_pb2'
  # @@protoc_insertion_point(class_scope:DeliveryCompleted)
  ))
_sym_db.RegisterMessage(DeliveryCompleted)

AUMessages = _reflection.GeneratedProtocolMessageType('AUMessages', (_message.Message,), dict(
  DESCRIPTOR = _AUMESSAGES,
  __module__ = 'amz_ups_pb2'
  # @@protoc_insertion_point(class_scope:AUMessages)
  ))
_sym_db.RegisterMessage(AUMessages)

UAMessages = _reflection.GeneratedProtocolMessageType('UAMessages', (_message.Message,), dict(
  DESCRIPTOR = _UAMESSAGES,
  __module__ = 'amz_ups_pb2'
  # @@protoc_insertion_point(class_scope:UAMessages)
  ))
_sym_db.RegisterMessage(UAMessages)


# @@protoc_insertion_point(module_scope)
