# Generated by Django 2.0.2 on 2018-04-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('trackingid', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('C', 'Created'), ('E', 'truck en route to warehouse'), ('W', 'truck waiting for package'), ('O', 'out for delivery')], max_length=30)),
                ('position_x', models.CharField(max_length=30, null=True)),
                ('position_y', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
