# Generated by Django 2.0.2 on 2018-04-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups_frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingid', models.CharField(max_length=30)),
                ('iteminfo', models.CharField(max_length=30)),
            ],
        ),
    ]
