# Generated by Django 2.0.2 on 2018-04-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups_frontend', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingid', models.CharField(max_length=30)),
                ('c_time', models.CharField(default='', max_length=100, null=True)),
                ('e_time', models.CharField(default='', max_length=100, null=True)),
                ('w_time', models.CharField(default='', max_length=100, null=True)),
                ('O_time', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
