# Generated by Django 2.0.4 on 2018-04-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups_frontend', '0004_auto_20180426_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='d_time',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='l_time',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='o_time',
            field=models.CharField(default='', max_length=101, null=True),
        ),
    ]
