# Generated by Django 2.0.4 on 2018-04-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups_frontend', '0005_auto_20180426_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.CharField(default='1', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='iteminfo',
            field=models.CharField(max_length=200),
        ),
    ]
