# Generated by Django 2.0.4 on 2018-04-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups_frontend', '0006_auto_20180426_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='o_time',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
